[browser]
gatherUsageStats = false
[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"
[client]
showErrorDetails = false
toolbarMode = "auto"
showSidebarNavigation = false
[runner]
magicEnabled = true
fastReruns = true
enforceSerializableSessionState = false
enumCoercion = "nameOnly"
[server]
folderWatchBlacklist = []
fileWatcherType = "auto"
cookieSecret = ""
headless = false
runOnSave = true
[theme]
textColor = "#042940"